spring.application.name=auth-service
server.port=4005

# OpenTelemetry Configuration
otel.sdk.disabled=false
otel.traces.exporter=otlp
otel.exporter.otlp.protocol=http/protobuf
otel.exporter.otlp.traces.endpoint=http://localhost:4318/v1/traces
otel.metrics.exporter=none
otel.service.name=${spring.application.name}
