spring.application.name=medical-records-service
server.port=8083

# OpenTelemetry Configuration
otel.sdk.disabled=false
otel.traces.exporter=otlp
otel.exporter.otlp.protocol=http/protobuf
otel.exporter.otlp.traces.endpoint=http://localhost:4318/v1/traces # Will be overridden by Docker Compose
otel.metrics.exporter=none
otel.service.name=${spring.application.name}

# gRPC server port (placeholder, adjust if needed)
grpc.server.port=9004
