spring.application.name=analytics-service

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

# OpenTelemetry Configuration
otel.sdk.disabled=false
otel.traces.exporter=otlp
otel.exporter.otlp.protocol=http/protobuf
otel.exporter.otlp.traces.endpoint=http://localhost:4318/v1/traces
otel.metrics.exporter=none
# It's good practice to explicitly set the service name for OpenTelemetry,
# though the spring-boot-starter often infers it from spring.application.name
otel.service.name=${spring.application.name}